<?php
declare(strict_types=1);


return [
    'test'      => [
        'CAREFREE_INSURANCE_CLIENT'    => 'test-service-main-00.test1.xiaozhu.com:80',
        'CAREFREE_INSURANCE_CLIENT_V2' => 'test-insurance-53.test2.xiaozhu.com:80',
        'CASH_PLEDGE_CLIENT'           => 'test-service-main-00.test1.xiaozhu.com:80',
        'COUPON_ACCOUNT_CLIENT'        => 'test-service-main-00.test1.xiaozhu.com:80',
        'CREDIT_CHECK_IN_CLIENT'       => 'test-service-main-00.test1.xiaozhu.com:80',
        'INSURANCE_CLIENT'             => 'test-service-main-00.test1.xiaozhu.com:80',
        'INSURANCE_CLIENT_V2'          => 'test-insurance-53.test2.xiaozhu.com:80',
        'INVOICE_CLIENT'               => 'test-service-main-00.test1.xiaozhu.com:80',
        'LODGE_UNIT_CLIENT'            => 'test-service-main-00.test1.xiaozhu.com:80',
        'USER_CLIENT'                  => 'test-service-main-00.test1.xiaozhu.com:80',
        'BLACK_USER_LIST_CLIENT'       => 'test-service-main-00.test1.xiaozhu.com:80',
        'ORDER_PAYMENT_CLIENT'         => 'test-service-main-00.test1.xiaozhu.com:80',
        'SMART_LOCK_CLIENT'            => 'test-service-main-00.test1.xiaozhu.com:80',
        'SMART_LOCK_CLIENT_V2'         => 'test-service-smart-00.test2.xiaozhu.com:80',
        'BOOK_ORDER_TENANT_CLIENT'     => 'test-service-main-00.test1.xiaozhu.com:80',
        'TENANT_CLIENT'                => 'test-service-main-00.test1.xiaozhu.com:80',
        'HOUSEKEEPER_CLIENT'           => 'test-service-clean-00.test1.xiaozhu.com:80',
        'RED_DOT_CLIENT'               => 'test-service-main-00.test1.xiaozhu.com:80',
        'COMMON_REDDOT_CLINT'          => 'test-service-bizcounter-01.test2.xiaozhu.com:80',
        'BOOK_ORDER_CLIENT'            => 'test-service-order-00.test2.xiaozhu.com:80',
        'OUT_BUY_CLIENT'               => 'test-service-main-00.test1.xiaozhu.com:80',
        'COMMENT_CLIENT_V2'            => 'test-service-comment-00.test2.xiaozhu.com:80',
        'ORDER_CHARGE_CLIENT'          => 'test-service-rent-00.test2.xiaozhu.com:80',
        'CHARGE_SERVICE_CLIENTV2'      => 'test-service-rent-00.test2.xiaozhu.com:80',
        'REMIND_CLIENT'                => 'test-xzremindbase-00.test1.xiaozhu.com:80',
        'OPERATIONS_CLIENT'            => 'test-service-main-00.test1.xiaozhu.com:80',
    ],
    'testEnv23' => [
        'CAREFREE_INSURANCE_CLIENT'    => 'test-service-main-env23.xiaozhu.com:80',
        'CAREFREE_INSURANCE_CLIENT_V2' => 'test-insurance-53.test2.xiaozhu.com:80',
        'CASH_PLEDGE_CLIENT'           => 'test-service-main-env23.xiaozhu.com:80',
        'COUPON_ACCOUNT_CLIENT'        => 'test-service-main-env23.xiaozhu.com:80',
        'CREDIT_CHECK_IN_CLIENT'       => 'test-service-main-env23.xiaozhu.com:80',
        'INSURANCE_CLIENT'             => 'test-service-main-env23.xiaozhu.com:80',
        'INSURANCE_CLIENT_V2'          => 'test-insurance-53.test2.xiaozhu.com:80',
        'INVOICE_CLIENT'               => 'test-service-main-env23.xiaozhu.com:80',
        'LODGE_UNIT_CLIENT'            => 'test-service-main-env23.xiaozhu.com:80',
        'USER_CLIENT'                  => 'test-service-main-env23.xiaozhu.com:80',
        'BLACK_USER_LIST_CLIENT'       => 'test-service-main-env23.xiaozhu.com:80',
        'ORDER_PAYMENT_CLIENT'         => 'test-service-main-env23.xiaozhu.com:80',
        'SMART_LOCK_CLIENT'            => 'test-service-main-env23.xiaozhu.com:80',
        'SMART_LOCK_CLIENT_V2'         => 'test-service-smart-00.test2.xiaozhu.com:80',
        'BOOK_ORDER_TENANT_CLIENT'     => 'test-service-main-env23.xiaozhu.com:80',
        'TENANT_CLIENT'                => 'test-service-main-env23.xiaozhu.com:80',
        'HOUSEKEEPER_CLIENT'           => 'test-service-clean-00.test1.xiaozhu.com:80',
        'RED_DOT_CLIENT'               => 'test-service-main-env23.xiaozhu.com:80',
        'COMMON_REDDOT_CLINT'          => 'test-service-bizcounter-01.test2.xiaozhu.com:80',
        'BOOK_ORDER_CLIENT'            => 'test-service-order-env23.xiaozhu.com:80',
        'OUT_BUY_CLIENT'               => 'test-service-main-env23.xiaozhu.com:80',
        'COMMENT_CLIENT_V2'            => 'test-service-comment-00.test2.xiaozhu.com:80',
        'ORDER_CHARGE_CLIENT'          => 'test-service-rent-env23.xiaozhu.com:80',
        'CHARGE_SERVICE_CLIENTV2'      => 'test-service-rent-env23.xiaozhu.com:80',
        'REMIND_CLIENT'                => 'test-xzremindbase-00.test1.xiaozhu.com:80',
        'OPERATIONS_CLIENT'            => 'test-service-main-env23.xiaozhu.com:80',
        'VIP_CLIENT'                   => 'test-service-user-env23.xiaozhu.com:80',
    ],
    'prod'      => [
        'CAREFREE_INSURANCE_CLIENT'    => 'service-main.xiaozhu.com:80',
        'CAREFREE_INSURANCE_CLIENT_V2' => 'service-insurance.xiaozhu.com:80',
        'CASH_PLEDGE_CLIENT'           => 'service-main.xiaozhu.com:80',
        'COUPON_ACCOUNT_CLIENT'        => 'service-main.xiaozhu.com:80',
        'CREDIT_CHECK_IN_CLIENT'       => 'service-main.xiaozhu.com:80',
        'INSURANCE_CLIENT'             => 'service-main.xiaozhu.com:80',
        'INSURANCE_CLIENT_V2'          => 'service-insurance.xiaozhu.com:80',
        'INVOICE_CLIENT'               => 'service-main.xiaozhu.com:80',
        'LODGE_UNIT_CLIENT'            => 'service-main.xiaozhu.com:80',
        'USER_CLIENT'                  => 'service-main.xiaozhu.com:80',
        'BLACK_USER_LIST_CLIENT'       => 'service-main.xiaozhu.com:80',
        'ORDER_PAYMENT_CLIENT'         => 'service-main.xiaozhu.com:80',
        'SMART_LOCK_CLIENT'            => 'service-main.xiaozhu.com:80',
        'SMART_LOCK_CLIENT_V2'         => 'service-smart.xiaozhu.com:80',
        'BOOK_ORDER_TENANT_CLIENT'     => 'service-main.xiaozhu.com:80',
        'TENANT_CLIENT'                => 'service-main.xiaozhu.com:80',
        'HOUSEKEEPER_CLIENT'           => 'service-clean.xiaozhu.com:80',
        'RED_DOT_CLIENT'               => 'service-main.xiaozhu.com:80',
        'COMMON_REDDOT_CLINT'          => 'service-bizcounter.xiaozhu.com:80',
        'OUT_BUY_CLIENT'               => 'service-main.xiaozhu.com:80',
        'COMMENT_CLIENT_V2'            => 'service-comment.xiaozhu.com:80',
        'ORDER_CHARGE_CLIENT'          => 'service-rent.xiaozhu.com:80',
        'CHARGE_SERVICE_CLIENTV2'      => 'service-rent.xiaozhu.com:80',
        'OPERATIONS_CLIENT'            => 'service-main.xiaozhu.com:80',
        'REMIND_CLIENT'                => 'service-remind.xiaozhu.com:80',
        'BOOK_ORDER_CLIENT'            => 'service-order.xiaozhu.com:80',

    ]
];
